name: Electron Release Builder

on:
  workflow_dispatch:
    inputs:
      increment:
        description: 'Increment type'
        required: true
        type: choice
        options:
          - "major"
          - "minor"
          - "patch"
          - "premajor"
          - "preminor"
          - "prepatch"
          - "prerelease"

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Setup env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 'lts/*'
          check-latest: true
      - run: npm ci
      - name: Uninstall unneeded dependencies
        run: npm un electronmon less-watch-compiler
      - name: Delete dev files
        run: |
          rm -fv css/*.less
        shell: bash

      # Setup version management
      - name: Setup Git
        run: |
          git config user.name "DemosJarco"
          git config user.email "1209494+demosjarco@users.noreply.github.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Increment version (from dropdown)
        run: npm version --sign-git-tag=true -f ${{ github.event.inputs.increment }}
      - run: git push --tags

      # Build
      - run: npm run pack:win
      - name: Compress package x32
        run: Compress-Archive -Path '.\builds\packaged\windows-auto-theme-win32-ia32' -DestinationPath '.\windows-auto-theme-x32.zip' -CompressionLevel Optimal
        shell: powershell
      - name: Compress package x64
        run: Compress-Archive -Path '.\builds\packaged\windows-auto-theme-win32-x64' -DestinationPath '.\windows-auto-theme-x64.zip' -CompressionLevel Optimal
        shell: powershell
      - name: Create installer x32
        run: npm run inst:win ia32
      - name: Create installer x64
        run: npm run inst:win x64

      # Upload Releases
      - name: Upload to Prereleases
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.increment == 'major' || github.event.inputs.increment == 'minor' || github.event.inputs.increment == 'patch' }}
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            builds/installers/windows-auto-theme-installer-x32.exe
            builds/installers/windows-auto-theme-installer-x64.exe
            builds/installers/windows-auto-theme-installer-x32.msi
            builds/installers/windows-auto-theme-installer-x64.msi
            windows-auto-theme-x32.zip
            windows-auto-theme-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to Releases
        uses: softprops/action-gh-release@v1
        if: ${{ github.event.inputs.increment == 'premajor' || github.event.inputs.increment == 'preminor' || github.event.inputs.increment == 'prepatch' || github.event.inputs.increment == 'prerelease' }}
        with:
          prerelease: false
          generate_release_notes: true
          files: |
            builds/installers/windows-auto-theme-installer-x32.exe
            builds/installers/windows-auto-theme-installer-x64.exe
            builds/installers/windows-auto-theme-installer-x32.msi
            builds/installers/windows-auto-theme-installer-x64.msi
            windows-auto-theme-x32.zip
            windows-auto-theme-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}