name: Test & Deploy
on:
  push:
    branches:
      - major
      - minor
      - patch
      - premajor
      - preminor
      - prepatch
      - prerelease
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      NODE_ENV: ${{ (contains(github.head_ref, 'pre') || contains(github.ref_name, 'pre') && 'development' || 'production') }}
    steps:
      - run: echo ${{ env.NODE_ENV }}
      # Setup env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm run build

      # Code QOL
      - run: npm run format:fix

      - run: npm test

  version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Setup env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Setup Git
        run: |
          git config user.name "DemosJarco"
          git config user.email "1209494+demosjarco@users.noreply.github.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - run: npm version --sign-git-tag=true ${{ github.head_ref || github.ref_name }}
      # - run: git push --tags

  build:
    needs: version
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [ia32, x64]
        type: [exe]
    steps:
      # Setup env
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - run: npm run build

      # Code QOL
      - run: npm run format:fix

      # Cleanup
      - name: Uninstall unneeded dependencies
        run: npm un electronmon eslint eslint-config-prettier eslint-plugin-json eslint-plugin-yml less-watch-compiler prettier
      - name: Delete dev files
        run: |
          rm -fv css/*.less .eslintrc.json .prettierrc.json less-watch-compiler.config.json
        shell: bash

      # Build
      - run: npm run pack:win -- --arch=${{ matrix.arch }}
      - run: Compress-Archive -Path '.\builds\packaged\windows-auto-theme-win32-${{ matrix.arch }}' -DestinationPath '.\windows-auto-theme-${{ matrix.arch }}.zip' -CompressionLevel Optimal
        shell: powershell
      - run: npm run inst:win ${{ matrix.arch }} ${{ matrix.type }}