on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  install-gyp:
    runs-on: windows-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     node: [latest, lts/*]
    #     msbuild: [x86, x64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: 'npm'
      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: Setup Git
        run: |
          git config user.name "DemosJarco"
          git config user.email "1209494+demosjarco@users.noreply.github.com"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - run: npm ci --fund=false
      - run: npm install UnityTech/windows-registry-node
      - run: git commit -am "Installed windows-registry"
      - run: git push