name: Test
on:
  push:
    paths-ignore:
      - '.vscode/**'
  pull_request:
    paths-ignore:
      - '.vscode/**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.win-ver }}
    strategy:
      fail-fast: false
      matrix:
        node-ver: [lts/*, latest]
        vs-ver: [2019, 2022]
        # win-target-ver: [10v1511, 10v1607, 10v1703, 10v1709, 10v1803, 10v1809, 10v1903, 10v2004, 10v21H1, 11v21H2, 11v22H2]
        win-target-ver: [10v1709, 10v1803, 10v1903, 10v2004, 10v21H1, 11v21H2, 11v22H2]
        include:
          - vs-ver: 2019
            vs-build-ver: '[16,17)'
            win-ver: windows-2019
          - vs-ver: 2022
            vs-build-ver: '[17,18)'
            vs-build-arch: x64
            win-ver: windows-latest
          # - win-target-ver: 10v1511
          #   win-target-build-ver: 10586
          #   nodert-package-name: '@nodert-win10/windows.devices.geolocation'
          # - win-target-ver: 10v1607
          #   win-target-build-ver: 14393
          #   nodert-package-name: '@nodert-win10-au/windows.devices.geolocation'
          # - win-target-ver: 10v1703
          #   win-target-build-ver: 15063
          #   nodert-package-name: '@nodert-win10-cu/windows.devices.geolocation'
          - win-target-ver: 10v1709
            win-target-build-ver: 16299
            nodert-package-name: '@nodert-win10-rs3/windows.devices.geolocation'
          - win-target-ver: 10v1803
            win-target-build-ver: 17134
            nodert-package-name: '@nodert-win10-rs4/windows.devices.geolocation'
          # - win-target-ver: 10v1809
          #   win-target-build-ver: 17763
          #   nodert-package-name: '@nodert-win10-rs5/windows.devices.geolocation'
          - win-target-ver: 10v1903
            win-target-build-ver: 18362
            nodert-package-name: '@nodert-win10-19h1/windows.devices.geolocation'
          - win-target-ver: 10v2004
            win-target-build-ver: 19041
            nodert-package-name: '@nodert-win10-20h1/windows.devices.geolocation'
          - win-target-ver: 10v21H1
            win-target-build-ver: 20348
            nodert-package-name: '@nodert-win10-21h1/windows.devices.geolocation'
          - win-target-ver: 11v21H2
            win-target-build-ver: 22000
            nodert-package-name: '@nodert-win11/windows.devices.geolocation'
          - win-target-ver: 11v22H2
            win-target-build-ver: 22621
            nodert-package-name: '@nodert-win11-22h2/windows.devices.geolocation'
        exclude:
          - win-target-ver: 10v1511
            vs-ver: 2022
          - win-target-ver: 10v1607
            vs-ver: 2022
          - win-target-ver: 10v1703
            vs-ver: 2022
          - win-target-ver: 10v1709
            vs-ver: 2022
          - win-target-ver: 10v1803
            vs-ver: 2022
          - win-target-ver: 11v21H2
            vs-ver: 2019
          - win-target-ver: 11v22H2
            vs-ver: 2019
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-ver }}
          check-latest: true
          cache: 'npm'

      - name: Setting up MsBuild x64 with vs${{ matrix.vs-ver }}
        uses: microsoft/setup-msbuild@v1.3
        with:
          vs-version: ${{ matrix.vs-build-ver }}
          # https://github.com/microsoft/setup-msbuild/blob/master/action.yml#L18 Only available in 17.0+
          msbuild-architecture: ${{ matrix.vs-build-arch }}
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.11
        with:
          sdk-version: ${{ matrix.win-target-build-ver }}
      # - uses: lukka/get-cmake@v.3.23.2
      # - name: Build new SDK
      #   shell: bash
      #   run: |
      #     cmake -DCMAKE_SYSTEM_VERSION=10.0.${{ matrix.win-target-build-ver }}.0
      #     cmake --build .

      - run: npm ci --fund=false
      - name: NodeRT Windows ${{ matrix.win-target-ver }} (${{ matrix.win-target-build-ver }})
        run: npm install ${{ matrix.nodert-package-name }}
      - run: npm run rebuild
      - run: npm test
        # Remove if on 2022-10-25 when 18.x reaches LTS
        # node:test is only available on 18 and up
        if: ${{ matrix.node-ver == 'latest' }}
