on:
  push:
    branches:
      - 'packaging'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        python-ver: [3.x]
        node-ver: [lts/*]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-ver }}
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-ver }}
          check-latest: true
          cache: 'npm'
      - uses: microsoft/setup-msbuild@v1
        with:
          msbuild-architecture: x64
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
        with:
          sdk-version: ${{ matrix.win-build-ver }}
      - run: npm ci
