name: Test
on:
  push:
    paths-ignore:
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - ".vscode/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        node-ver: [lts/*, latest]
        # win-build-ver: [1511, 1607, 1703, 1709, 1803, 1809, 1903, 2004]
        win-ver: [1511, 1607, 1703, 1709, 1803, 2004]
        include:
          - win-ver: 1511
            win-build-ver: 10586
            nodert-package-name: '@nodert-win10/windows.devices.geolocation'
          - win-ver: 1607
            win-build-ver: 14393
            nodert-package-name: '@nodert-win10-au/windows.devices.geolocation'
          - win-ver: 1703
            win-build-ver: 15063
            nodert-package-name: '@nodert-win10-cu/windows.devices.geolocation'
          - win-ver: 1709
            win-build-ver: 16299
            nodert-package-name: '@nodert-win10-rs3/windows.devices.geolocation'
          - win-ver: 1803
            win-build-ver: 17134
            nodert-package-name: '@nodert-win10-rs4/windows.devices.geolocation'
          # - win-ver: 1809
          #   win-build-ver: 17763
          #   nodert-package-name: '@nodert-win10-rs5/windows.devices.geolocation'
          # - win-ver: 1903
          #   win-build-ver: 18362
          #   nodert-package-name: '@nodert-win10-19h1/windows.devices.geolocation'
          - win-ver: 2004
            win-build-ver: 19041
            nodert-package-name: '@nodert-win10-20h1/windows.devices.geolocation'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-ver }}
          check-latest: true
          cache: 'npm'

      - uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.7
        with:
          sdk-version: ${{ matrix.win-build-ver }}
      # - uses: lukka/get-cmake@v.3.23.2
      # - name: Build new SDK
      #   shell: bash
      #   run: |
      #     cmake -DCMAKE_SYSTEM_VERSION=10.0.${{ matrix.win-build-ver }}.0
      #     cmake --build .

      - run: npm ci --fund=false
      - name: nodeRT Windows 10 ${{ matrix.win-ver }} (${{ matrix.win-ver }})
        run: npm install ${{ matrix.nodert-package-name }}