name: Test
on:
  push:
    paths-ignore:
      - ".vscode/**"
  pull_request:
    paths-ignore:
      - ".vscode/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.win-ver }}
    strategy:
      fail-fast: false
      matrix:
        # node-ver: [lts/*, latest]
        node-ver: [lts/*]
        vs-ver: [2019, 2022]
        # win-target-ver: [1511, 1607, 1703, 1709, 1803, 2004]
        win-target-ver: [1703, 1709, 1803, 2004]
        include:
          - vs-ver: 2019
            vs-build-ver: '[16,17)'
            win-ver: windows-2019
          - vs-ver: 2022
            vs-build-ver: '[17,18)'
            vs-build-arch: x64
            win-ver: windows-latest
          # - win-target-ver: 1511
          #   win-target-build-ver: 10586
          #   nodert-package-name: '@nodert-win10/windows.devices.geolocation'
          # - win-target-ver: 1607
          #   win-target-build-ver: 14393
          #   nodert-package-name: '@nodert-win10-au/windows.devices.geolocation'
          - win-target-ver: 1703
            win-target-build-ver: 15063
            nodert-package-name: '@nodert-win10-cu/windows.devices.geolocation'
          - win-target-ver: 1709
            win-target-build-ver: 16299
            nodert-package-name: '@nodert-win10-rs3/windows.devices.geolocation'
          - win-target-ver: 1803
            win-target-build-ver: 17134
            nodert-package-name: '@nodert-win10-rs4/windows.devices.geolocation'
          # - win-target-ver: 1809
          #   win-target-build-ver: 17763
          #   nodert-package-name: '@nodert-win10-rs5/windows.devices.geolocation'
          # - win-target-ver: 1903
          #   win-target-build-ver: 18362
          #   nodert-package-name: '@nodert-win10-19h1/windows.devices.geolocation'
          - win-target-ver: 2004
            win-target-build-ver: 19041
            nodert-package-name: '@nodert-win10-20h1/windows.devices.geolocation'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          check-latest: true
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-ver }}
          check-latest: true
          cache: 'npm'

      - name: Setting up MsBuild x64 with vs${{ matrix.vs-ver }}
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: ${{ matrix.vs-build-ver }}
          # https://github.com/microsoft/setup-msbuild/blob/master/action.yml#L18 Only available in 17.0+
          msbuild-architecture: ${{ matrix.vs-build-arch }}
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.7
        with:
          sdk-version: ${{ matrix.win-target-build-ver }}
      # - uses: lukka/get-cmake@v.3.23.2
      # - name: Build new SDK
      #   shell: bash
      #   run: |
      #     cmake -DCMAKE_SYSTEM_VERSION=10.0.${{ matrix.win-target-build-ver }}.0
      #     cmake --build .

      - run: npm ci --fund=false
        env:
          npm_config_target: 1.2.3
          npm_config_arch: x64
          npm_config_target_arch: x64
          npm_config_disturl: https://electronjs.org/headers
          npm_config_runtime: electron
          npm_config_build_from_source: true
      - name: NodeRT Windows 10 ${{ matrix.win-target-ver }} (${{ matrix.win-target-build-ver }})
        run: npm install ${{ matrix.nodert-package-name }}